<?php

/**
 * @file
 * Contains smmg_sandbox.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function smmg_sandbox_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the smmg_sandbox module.
    case 'help.page.smmg_sandbox':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Sandbox Module for Testing') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function smmg_sandbox_theme() {
  return [
    'smmg_sandbox' => [
      'render element' => 'children',
    ],
  ];
}
